### ISSUE TITLE
About model parameter initialization on different process

### ISSUE THREAD

**Issue by yyk-wew** [rentainhe/pytorch-distributed-training#1]
您好：

有关多个进程上对模型的实例化我有一点小疑问。

https://github.com/rentainhe/pytorch-distributed-training/blob/33d04b235bf6711b1c5fd21c685a927bd4a2fbfa/distributed_mp.py#L66-L73

如代码所示，模型的实例化是在**main_worker**函数中实现的。但DDP要求多个进程上的模型参数保持一致。假设我的多个进程使用不同的随机种子，模型实例化过程中对参数进行随机初始化是否会导致进程上的模型参数不一致？

**Comment by rentainhe** [comment]
很好的问题，我这边验证一下

我的印象里是，为了增加模型采样数据的随机性，在这里增加了一个init_seed函数，对不同进程设置不同的随机种子，让sampler可以在不同进程用不同的random seed进行数据采样，有利于 training

**Comment by rentainhe** [comment]
感谢你的issue，我这两天会update一下这个repo，因为我发现我刚刚自己clone下来运行的时候有问题，已经debug解决了，我这边会参考一些其他优秀repo的ddp写法，这两天update一下，然后验证一下你的问题

**Comment by rentainhe** [comment]
> 您好：
> 
> 有关多个进程上对模型的实例化我有一点小疑问。
> 
> https://github.com/rentainhe/pytorch-distributed-training/blob/33d04b235bf6711b1c5fd21c685a927bd4a2fbfa/distributed_mp.py#L66-L73
> 
> 如代码所示，模型的实例化是在**main_worker**函数中实现的。但DDP要求多个进程上的模型参数保持一致。假设我的多个进程使用不同的随机种子，模型实例化过程中对参数进行随机初始化是否会导致进程上的模型参数不一致？

我会及时验证一下你的问题

**Comment by yyk-wew** [comment]
多谢回复以及实验，期待你的进一步结果~

**Comment by rentainhe** [comment]
> 多谢回复以及实验，期待你的进一步结果~

好的，我这个周末会进行相关的验证，然后我还发现我这个repo的一些问题，我打算参考一下以下两份代码重新整理一下ddp训练的代码：
- [Swin-Transformer](https://github.com/microsoft/Swin-Transformer)
- [DeiT](https://github.com/facebookresearch/deit)

到时候会整理一个更加clean的repo，提供给您

也许这里面训练也有一些细节，我会把我查阅的相关资料也整理进去，感谢关注

**Comment by yyk-wew** [comment]
您好，我自己做了个简单的实验，正好分享一下结果，供您参考。

我参照的代码为pytorch给出的Imagenet训练代码：
+ [Imagenet](https://github.com/pytorch/examples/tree/master/imagenet)

该代码的架构与您仓库中的版本是类似的，都是在**main_worker**函数中实例化网络模型。
在该架构下，我自定义了一个卷积层，并对卷积层的参数进行kaiming初始化。
```python
class testModule(nn.Module):
    def __init__(self):
        super(testModule, self).__init__()

        self.conv = nn.Conv2d(1, 1, (3,3), stride=2)
        nn.init.kaiming_normal_(self.conv.weight, mode='fan_out', nonlinearity='relu')
```

在DDP的环境下输出不同进程中网络的参数，得到的结果如下：

```python
Use GPU: 1 for training
Use GPU: 0 for training
Use GPU: 2 for training
Use GPU: 3 for training
1 Parameter containing:
tensor([[[[-0.4286, -0.5690,  0.1758],
          [-0.5455,  0.2774, -0.0294],
          [ 0.1396, -0.4146, -0.0624]]]], requires_grad=True)
0 Parameter containing:
tensor([[[[ 0.3810, -0.0909, -0.0175],
          [ 0.3012, -0.5628,  0.0225],
          [-1.0392,  0.4203,  0.0202]]]], requires_grad=True)
2 Parameter containing:
tensor([[[[-0.8210, -0.9359, -0.0747],
          [-0.2131,  0.3568,  0.3749],
          [ 0.3743, -0.4720,  0.2649]]]], requires_grad=True)
3 Parameter containing:
tensor([[[[ 0.2036,  0.7038, -0.5586],
          [-1.2837, -0.4133,  0.2432],
          [ 0.3420,  0.0973, -0.1059]]]], requires_grad=True)
```

可以看到如果先开启进程，再在各个进程上的初始化网络模型，模型的参数确是不同的。
但这份pytorch给出的Imagenet训练代码是能正确运行的，其中具体的原理我还并不清楚，以待探讨。

**Comment by rentainhe** [comment]
> 您好，我自己做了个简单的实验，正好分享一下结果，供您参考。
> 
> 我参照的代码为pytorch给出的Imagenet训练代码：
> 
> * [Imagenet](https://github.com/pytorch/examples/tree/master/imagenet)
> 
> 该代码的架构与您仓库中的版本是类似的，都是在**main_worker**函数中实例化网络模型。
> 在该架构下，我自定义了一个卷积层，并对卷积层的参数进行kaiming初始化。
> 
> ```python
> class testModule(nn.Module):
>     def __init__(self):
>         super(testModule, self).__init__()
> 
>         self.conv = nn.Conv2d(1, 1, (3,3), stride=2)
>         nn.init.kaiming_normal_(self.conv.weight, mode='fan_out', nonlinearity='relu')
> ```
> 
> 在DDP的环境下输出不同进程中网络的参数，得到的结果如下：
> 
> ```python
> Use GPU: 1 for training
> Use GPU: 0 for training
> Use GPU: 2 for training
> Use GPU: 3 for training
> 1 Parameter containing:
> tensor([[[[-0.4286, -0.5690,  0.1758],
>           [-0.5455,  0.2774, -0.0294],
>           [ 0.1396, -0.4146, -0.0624]]]], requires_grad=True)
> 0 Parameter containing:
> tensor([[[[ 0.3810, -0.0909, -0.0175],
>           [ 0.3012, -0.5628,  0.0225],
>           [-1.0392,  0.4203,  0.0202]]]], requires_grad=True)
> 2 Parameter containing:
> tensor([[[[-0.8210, -0.9359, -0.0747],
>           [-0.2131,  0.3568,  0.3749],
>           [ 0.3743, -0.4720,  0.2649]]]], requires_grad=True)
> 3 Parameter containing:
> tensor([[[[ 0.2036,  0.7038, -0.5586],
>           [-1.2837, -0.4133,  0.2432],
>           [ 0.3420,  0.0973, -0.1059]]]], requires_grad=True)
> ```
> 
> 可以看到如果先开启进程，再在各个进程上的初始化网络模型，模型的参数确是不同的。
> 但这份pytorch给出的Imagenet训练代码是能正确运行的，其中具体的原理我还并不清楚，以待探讨。

非常感谢你提供的参考，我这边也是由于在工作和开源一个新的repo，比较忙碌，还没来得及验证，非常抱歉
但是我参考一些优秀的代码库，例如Swin-Transformer，deit，他们是将model在main函数里先初始化，然后用torch.nn.parallel.DistributedDataParallel包裹，我不确定这个实现是否会保证一个统一的初始化，有待验证，可能他们是先初始化model再开启进程

**Comment by yyk-wew** [comment]
> 他们是将model在main函数里先初始化，然后用torch.nn.parallel.DistributedDataParallel包裹

您好，我今天看到您的回复，发现我之前的实验做的有问题，重做了实验后解决了我的疑问，十分感谢！在此分享我的结果。

还是使用上次回复中提到的**testModule**来做实验，只是在mainworker中打印模型参数的地方做了改动：
```python
    model = testModule().to("cuda:"+str(gpu))
    print(gpu, model.conv.weight)
    ddp_model = torch.nn.parallel.DistributedDataParallel(model)
    print(gpu, ddp_model.module.conv.weight)
```
在**main_worker**中，用DDP包裹之前和之后分别打印模型参数。
```
Use GPU: 0 for training
Use GPU: 1 for training
1 Parameter containing:
tensor([[[[ 0.8718, -0.2182, -0.7143],
          [-0.2333,  0.0485, -0.7830],
          [ 0.0448, -0.4794,  0.3542]]]], device='cuda:1', requires_grad=True)
0 Parameter containing:
tensor([[[[-0.3931,  0.0702,  0.0811],
          [-0.3008, -0.0213, -0.5177],
          [-0.7133, -0.2661,  0.3069]]]], device='cuda:0', requires_grad=True)
1 Parameter containing:
tensor([[[[-0.3931,  0.0702,  0.0811],
          [-0.3008, -0.0213, -0.5177],
          [-0.7133, -0.2661,  0.3069]]]], device='cuda:1', requires_grad=True)
0 Parameter containing:
tensor([[[[-0.3931,  0.0702,  0.0811],
          [-0.3008, -0.0213, -0.5177],
          [-0.7133, -0.2661,  0.3069]]]], device='cuda:0', requires_grad=True)
```
从结果可以看到，实际上DDP包裹之后模型参数就统一了。DDP应该是把rank0的进程中的模型参数广播到其他进程中，实现了参数的统一。

所以，无论是Swin-Transformer的写法还是您原repo中的写法都是正确的，参数都会统一。

**Comment by rentainhe** [comment]
> > 他们是将model在main函数里先初始化，然后用torch.nn.parallel.DistributedDataParallel包裹
> 
> 您好，我今天看到您的回复，发现我之前的实验做的有问题，重做了实验后解决了我的疑问，十分感谢！在此分享我的结果。
> 
> 还是使用上次回复中提到的**testModule**来做实验，只是在mainworker中打印模型参数的地方做了改动：
> 
> ```python
>     model = testModule().to("cuda:"+str(gpu))
>     print(gpu, model.conv.weight)
>     ddp_model = torch.nn.parallel.DistributedDataParallel(model)
>     print(gpu, ddp_model.module.conv.weight)
> ```
> 
> 在**main_worker**中，用DDP包裹之前和之后分别打印模型参数。
> 
> ```
> Use GPU: 0 for training
> Use GPU: 1 for training
> 1 Parameter containing:
> tensor([[[[ 0.8718, -0.2182, -0.7143],
>           [-0.2333,  0.0485, -0.7830],
>           [ 0.0448, -0.4794,  0.3542]]]], device='cuda:1', requires_grad=True)
> 0 Parameter containing:
> tensor([[[[-0.3931,  0.0702,  0.0811],
>           [-0.3008, -0.0213, -0.5177],
>           [-0.7133, -0.2661,  0.3069]]]], device='cuda:0', requires_grad=True)
> 1 Parameter containing:
> tensor([[[[-0.3931,  0.0702,  0.0811],
>           [-0.3008, -0.0213, -0.5177],
>           [-0.7133, -0.2661,  0.3069]]]], device='cuda:1', requires_grad=True)
> 0 Parameter containing:
> tensor([[[[-0.3931,  0.0702,  0.0811],
>           [-0.3008, -0.0213, -0.5177],
>           [-0.7133, -0.2661,  0.3069]]]], device='cuda:0', requires_grad=True)
> ```
> 
> 从结果可以看到，实际上DDP包裹之后模型参数就统一了。DDP应该是把rank0的进程中的模型参数广播到其他进程中，实现了参数的统一。
> 
> 所以，无论是Swin-Transformer的写法还是您原repo中的写法都是正确的，参数都会统一。

非常感谢你的实验分享，之前这一些细节也是我没有注意到的，涨知识！我会把这个mark一下，找个时间我会重构这个repo，最近也在忙碌一些别的开源项目，其实这个repo里的一些模型训练，我还没有完全掌握细节，之前是跑过4卡的resnet18，但是精度上总不是很让人满意，可能ddp还有许多细节是我没有注意到的，例如与gradient-accumulation-steps的结合，syncBN的使用等，之前没有来得及验证细节

**Comment by yyk-wew** [comment]
Thumbs-up！期待你重构后的repo~
